### ISSUE TITLE
feature: Please consider adding a dark mode

### ISSUE THREAD

**Issue by KerfuffleV2** [menhera-org/TabArray#1]
Disabling resist fingerprinting and setting `ui.systemUsesDarkTheme` did not seem to help. It doesn't appear the addon will respect a user's dark mod preference currently. Please correct me if I'm wrong.

**Comment by metastable-void** [comment]
Yes, you are right about a dark mode being not supported, and I'l be working on it soon.

**Comment by metastable-void** [comment]
Please wait before the addon is updated on addons.mozilla.org.

**Comment by KerfuffleV2** [comment]
@metastable-void Hey, I just wanted to say thanks for adding that! It's appreciated.
