### ISSUE TITLE
Index tab feature issues

### ISSUE THREAD

**Issue by fmigneault** [menhera-org/TabArray#10]
I have noticed the following 2 issues with the new "index tab" feature:
1. When the setting is modified to enable "index tab", reverting it to anything else doesn't make the tabs go away (hidden).
2. After clicking on a "closed" index tab to open the contained tabs (this works well), clicking the index again doesn't close them back.   Instead, the browser seem to do a very quick flicker (quick switch back and forth between the index tab and another?). 

For point (2), if I right click on the index tab and select "Hide this container", then it does the expected behaviour of rolling back the tabs under the index, but this is more clicks and not as obvious.

Thank you for adding this feature. It is very convenient.

**Comment by metastable-void** [comment]
Fixed in https://github.com/menhera-org/TabArray/commit/3ed20f688eaa7114bab6193db1805492d91d95af.
