### ISSUE TITLE
No icons in toolbar

### ISSUE THREAD

**Issue by zorrohere** [menhera-org/TabArray#11]
Addon seems broken for me, after installing and restarting firefox, I still don't see any icons or new options from this addon. I also tried customizing toolbar but don't see options there as well. I can right click on tab and hide container group from existing containers addon, that's the only new option visible to me. If I create new tab from hidden container group then all hidden tabs become visible. Let me know what additional info you need. I have tried this addon in latest FF and Developer versions.

**Comment by metastable-void** [comment]
I would like to know more to fix this issue. Could you show me the following information here?

- The list of the addons you are using other than this
- Open `about:debugging` when this issue occurs and copy the console output you can find in This Firefox > Container Tab Groups > Inspect.

**Comment by metastable-void** [comment]
For your information, the button/icon is to be displayed in the rightmost part of the tab bar, by default, as shown below.

![Screen Shot 2022-08-27 at 22 36 49](https://user-images.githubusercontent.com/54881138/187032627-5fe96160-d2cb-4438-80ed-f3d8ad0f98cc.png)

The button with theree dots is it.

**Comment by metastable-void** [comment]
Closing as being stale. Please reopen the issue if the problem persists.
