### ISSUE TITLE
Show all tabs of the window in the window selection menu.

### ISSUE THREAD

**Issue by umgpy** [menhera-org/TabArray#122]
**Is your feature request related to a problem? Please describe.**
Windows section should show all the tabs in them along with the count, unlike now which only shows a single current tab in that window.

**Describe the solution you'd like**
It would be helpful to see all the tab groups both hidden and open in that window.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by metastable-void** [comment]
![Screenshot 2023-03-08 at 16 08 41](https://user-images.githubusercontent.com/54881138/223644347-6898a8ec-3ac4-4edd-9e07-834a2b84a5d8.png)

In new "Windows" view, you can select a window and view all the tabs of it.

**Comment by umgpy** [comment]
Thank you so much. This is perfect!
