### ISSUE TITLE
[Feature request]Add an shortcut of Panorama Grid and makes container editable.

### ISSUE THREAD

**Issue by PaTTeeL** [menhera-org/TabArray#123]
**Is your feature request related to a problem? Please describe.**
Is there any shortcut icon to enter "Open Panorama Grid". With out shortcut, it's hard to make arrangement or switch to certain tabs.
![image](https://user-images.githubusercontent.com/9150277/218277401-cef5114c-947e-4f47-8072-084d5c5023ba.png)

**Describe the solution you'd like**
Can we add an shortcut icon for "Open Panorama Grid" like ["Panorama Tab Groups"](https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/) does, and make the tab container editable by drag and drop ?

**Additional context**
Screenshot of panorama tab groups :
![image](https://user-images.githubusercontent.com/9150277/218273988-fc8f8f53-57a1-48fb-810e-ba2d32fb264b.png)
An icon for Panorama Grid and tabs can be drag and drop between different tab groups.

**Comment by metastable-void** [comment]
Added a button to open Panorama Grid. Also added a keyboard shortcut (Ctrl+Alt+P).
![Screenshot 2023-02-15 at 17 40 08](https://user-images.githubusercontent.com/54881138/218976210-f409ff43-d386-4eb9-8c29-c8261824959a.png)

**Comment by metastable-void** [comment]
Now we can create, delete and edit containers in Panorama Grid.
