### ISSUE TITLE
Switchable sorting function

### ISSUE THREAD

**Issue by zen0bit** [menhera-org/TabArray#162]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when my panel traveling.

I usually have a *lot* of tabs. If i open link to site bounded to container this tabs travel alllll the way to right place, it can get up to minute..
  

**Describe the solution you'd like**
Switchable sorting functions, so tabs can open as in base firefox and not go to own group

**Comment by metastable-void** [comment]
Also, the tab sorting function is I think not fully optimized, so it could be faster.

I will add a preference to turn off tab sorting.

**Comment by metastable-void** [comment]
Updated to use the state-of-the-art sorting algorithm. #1867e711c70b38fe2e3d87785ad555547063f9c4

**Comment by metastable-void** [comment]
This should be faster up to 100x, when we have hundreds of tabs.

**Comment by metastable-void** [comment]
For perfection, I just added an option to disable sorting of tabs (https://github.com/menhera-org/TabArray/commit/5bd10f674443f4d1bbd9654db6f99284f159bfae).

**Comment by metastable-void** [comment]
This feature is included in the next 11.6.0 release.
https://github.com/menhera-org/TabArray/discussions/183
