### ISSUE TITLE
Super group of Tabs

### ISSUE THREAD

**Issue by umgpy** [menhera-org/TabArray#163]
**Is your feature request related to a problem? Please describe.**
Sometimes we want different container tabs together in a single super group. Example - Work Super tab can have work mail container, github container, google. And Study work container can also have github and google.

Under the current setup the google, mail and github tab would be sorted and grouped together. A super tab group should help solve this problem. 

**Describe the solution you'd like**
Possibly add a tag of a super tab to the tab name.

**Describe alternatives you've considered**
Each super tab in a window, thus any new tab to the super container should be sent to the corresponding window. This makes it super window though but in case firefox doesn't allow the former this method could still be useful. 

**Additional context**
None

**Comment by metastable-void** [comment]
GIving tabs visible tags for supergroups does not seem to be possible due to API limitation, but giving groups names like `Container (Group 1)` is possible.
