### ISSUE TITLE
No Container Tab Group

### ISSUE THREAD

**Issue by GunGunGun** [menhera-org/TabArray#165]
**Is your feature request related to a problem? Please describe.**
Sometimes it's better to group No Container Tab Groups because:
- We just want to group tabs from the same website
- From the same tag, for example coding, workout..

**Describe the solution you'd like**
It would be great if we can create No Container Tab Groups just to group our tab and not using anything related to Container because container requires us to login again if we use the same website and same account

**Describe alternatives you've considered**
If it's possible, tagging a group of tab with a class and coloring them with css would be able to achive this type of tab group without using container feature, if this is possible with WebExtension tho because I don't know about WE limitations

**Additional context**
I think Simple Tab Group addon implemented something like this, would be great for TabArray to have it and becomes more versatile tho: https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/

**Comment by metastable-void** [comment]
We are now considering supergroups & subgroups feature in #167.

**Comment by metastable-void** [comment]
One limitation of the WebExtensions API is that because we use containers for theming tabs the color and the icon would be the same for subgroups inside one container.

**Comment by metastable-void** [comment]
We will implement subgroups as Tags in #168.

**Comment by GunGunGun** [comment]
> We will implement subgroups as Tags in #168.

Thank you, I can't wait to see this feature, thank you for making such a great addon!
