### ISSUE TITLE
Supergroups and subgroups

### ISSUE THREAD

**Issue by metastable-void** [menhera-org/TabArray#168]
### Discussed in https://github.com/menhera-org/TabArray/discussions/167

<div type='discussions-op-text'>

<sup>Originally posted by **metastable-void** April  1, 2023</sup>
As in #163, we should be able to have a supergroup including multiple containers.

As in #165, we should consider subgroups inside a container to sort tabs in a single container.

Both features would together work better.</div>

**Comment by metastable-void** [comment]
- Group related containers into a supergroup
- Allow tagging of tabs to group tabs in a container

**Comment by metastable-void** [comment]
We would call supergroups "Groups", and call subgroups "Tags".

**Comment by metastable-void** [comment]
We could allow use of tags across containers, and allow search by tags.

**Comment by metastable-void** [comment]
Subgroups would be super convenient in private windows.

**Comment by metastable-void** [comment]
_Groups_ could be implemented as follows:

```typescript
export type Supergroup = {
  cookieStoreIds: number[];
  name: string;
};
```

**Comment by metastable-void** [comment]
As for _Tags_, we should assign the same tag as the opener tab for a tab opened by another tab.

**Comment by metastable-void** [comment]
We could store a _Tag_ for a tab using `browser.sessions.setTabValue()`/`browser.sessions.getTabValue()`.

**Comment by metastable-void** [comment]
![Screenshot 2023-04-07 at 19 23 09](https://user-images.githubusercontent.com/54881138/230592722-c5e3bcd3-7d31-4073-a468-ec149a247c81.png)

Implementing _Groups_ (supergroups) of containers.

**Comment by GunGunGun** [comment]
Thanks very much for working hard, this new feature is very promising!

If you need a tester, I can test this beta/nightly build and try to report bugs if possible.

**Comment by metastable-void** [comment]
This is the unsigned build of the current version of the supergroup feature. Tests welcome.

[container-tab-groups-31ffb255acf2d62a1e94f87e7ad0a3ecf4203fb3.prod.xpi.zip](https://github.com/menhera-org/TabArray/files/11182419/container-tab-groups-31ffb255acf2d62a1e94f87e7ad0a3ecf4203fb3.prod.xpi.zip)

**Comment by metastable-void** [comment]
Implemented the model for _Tags_.

```typescript
export type TagType = {
  tagId: number;
  name: string;
};

export type TagStorageType = {
  [tagId: number]: TagType;
};
```

**Comment by metastable-void** [comment]
People tend to have thousands of tabs, so we need to be careful about memory usage 😭

**Comment by metastable-void** [comment]
When the total rewrite of the add-on is finished memory usage should be smaller, but for now...

**Comment by metastable-void** [comment]
Tag (subgroup) feature is here! Testing welcome.
[container-tab-groups-7f6f7df976ec5b852f4d179f02c5d3b289a00796.prod.xpi.zip](https://github.com/menhera-org/TabArray/files/11261895/container-tab-groups-7f6f7df976ec5b852f4d179f02c5d3b289a00796.prod.xpi.zip)

**Comment by GunGunGun** [comment]
> Tag (subgroup) feature is here! Testing welcome. [container-tab-groups-7f6f7df976ec5b852f4d179f02c5d3b289a00796.prod.xpi.zip](https://github.com/menhera-org/TabArray/files/11261895/container-tab-groups-7f6f7df976ec5b852f4d179f02c5d3b289a00796.prod.xpi.zip)

Thank you for your hard work, the tagging feature looks really great.

Subgroup feature works as expected, but I guess it's a bit hard for me to use, but I was able to create new group and subgroups for that group, which is wonderful! I'm looking forward to see the stable version!

**Comment by metastable-void** [comment]
This is the features and improvements for the next 11.6.0 release.

https://github.com/menhera-org/TabArray/discussions/183
