### ISSUE TITLE
container proxy

### ISSUE THREAD

**Issue by loveqianool** [menhera-org/TabArray#184]

**Comment by metastable-void** [comment]
Is it correct that you want per-container proxy settings feature integrated into Container Tab Groups extension? That thing is the one I have already considered, and I think it is a good idea.

**Comment by metastable-void** [comment]
As enabling it by default would conflict with "Container Proxy" extension, I will consider adding it as an optional feature.

**Comment by metastable-void** [comment]
Merged #191.
