### ISSUE TITLE
Unable to select "No Container"

### ISSUE THREAD

**Issue by izenn** [menhera-org/TabArray#190]
**Describe the bug**
After yesterday's release, i am no longer able to select "No Container" when i am prompted to select a container for a new tab

**To Reproduce**
open site that prompts for container selection, try to click "No Container"

**Expected behavior**
I should be able to select "No Container"

**Screenshots**
n/a

**Console outputs**
<img width="1719" alt="Screenshot 2023-04-25 at 7 59 19 AM" src="https://user-images.githubusercontent.com/744288/234285097-f2903aaf-2d0a-461a-a66c-104e8fe633f6.png">

Note that reopen_tab_in_container will increment, but nothing actually happens

**Firefox (please complete the following information):**

 - OS: macos
 - Browser edition and version general release 112.0.1
 - Extension version 11.6.1

**Additional context**

**Comment by metastable-void** [comment]
This issue is confirmed and fixed in https://github.com/menhera-org/TabArray/commit/5e44ad6230abc0706c4bb97b530eb8475cce9192.

Version 11.6.2 containing the fix will be released later today.

**Comment by metastable-void** [comment]
Released as [11.6.2](https://github.com/menhera-org/TabArray/releases/tag/v11.6.2).
