### ISSUE TITLE
Auto collapse unselected groups

### ISSUE THREAD

**Issue by maverick74** [menhera-org/TabArray#195]
**Is your feature request related to a problem? Please describe.**
Some users never work in two groups at the same time. Either they're working on one group or they're working on the other.

As such...

**Describe the solution you'd like**
I would like to suggest a auto-collapse/auto-hide all other groups a user is currently not working on.

**Describe alternatives you've considered**
Chromium-Based browsers

**Additional context**
If the "Index Tab" feature works as the chromium-like tab groups do - #111 - , it would be of great help and solve the "quick switch between groups" problem ( naturally, without a quick switch there's no point in implementing this auto-collapse )

**Comment by metastable-void** [comment]
In #10, we have implemented quick show/hide containers via clicks on index tabs.

**Comment by maverick74** [comment]
> In #10, we have implemented quick show/hide containers via clicks on index tabs.

I'm sorry! I didn't understand the feature correctly! I had to try it again... :)

But still, there's no auto-colapse of a group when we select a tab from another group.
And, also, i think it would make perfect sense to hide the "index tabs" of empty groups

**Comment by JohnLGalt** [comment]
If auto-collapse were to be implemented, I would like to have it as an **option**, versus just enabled. I usually prefer to collapse my containers manually.

**Comment by maverick74** [comment]
> I would like to have it as an **option**, versus just enabled.

Naturally!!! It never crossed my mind to have it forced on everyone!!! :)
Options are good so that anyone can have it "their way"

**Comment by metastable-void** [comment]
Implemented in https://github.com/menhera-org/TabArray/commit/4f57930f4931a75b71d0d9f584cadec4195927d5.

**Comment by metastable-void** [comment]
Released as https://github.com/menhera-org/TabArray/releases/tag/v11.8.0.

**Comment by maverick74** [comment]
I'm sorry for not testing it earlier (other things got in the way... )

First: **THANK YOU!!!**

There's one thing, however, i don't know how it should be deal with:

A container that has just one tab which happens to be pinned.
This "Container Tab" should also be hidden because if not, when one selects it, it somehow passes to the next...

Is this doable? Does it makes sense?

(sorry for such a short description... I'm in a hurry)
