### ISSUE TITLE
Sync between computers

### ISSUE THREAD

**Issue by bonnepioche** [menhera-org/TabArray#197]
Hi!
I am a Simple Tab Group user and there is a feature that STG is missing: the capacity to sync groups between computers.

I would love if the container groups created by the addon are synced between my 2 computers (professional and personnal). Did I mentionned my phone? ;)
You see, my workflow implies that I can keep on working on both computers, meaning that my tab groups follow me.

**Describe alternatives you've considered**
The only workaroud is to sync manually the tab groups, that's what I am doing with STG. This annoying enough for me to be willing to change.

Keep up the good work!

Pat

**Comment by metastable-void** [comment]
Considering adding this to synced storage:

```typescript
type SyncedContainerList = {
  name: string;
  userContextIds: {
    [installationId: string]: Uint32,
  },
}[];
```

I opt to exclude temporary containers from syncing, though.

**Comment by metastable-void** [comment]
It seems separate storage items for each identity is preferred.

**sync area**

```
__identity__.<identity UUID>: {
  id: <identity UUID>,
  name: <name>,
  deletedTime: null | integer (unix time in milliseconds),
}
```

**local area**

```
syncedIdentityMap: {
  [userContextId]: <identity UUID>,
}
```

**Comment by metastable-void** [comment]
Implemented the initial version of container sync: https://github.com/menhera-org/TabArray/commit/936c91427eefe1705245cd1462cb647e6519ce0e

Since sync storage quota is limited, per-container settings, groups and tags are not synced.
