### ISSUE TITLE
Feature Request:  Hide empty containers

### ISSUE THREAD

**Issue by ackstorm23** [menhera-org/TabArray#220]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

The ability to hide empty containers from the list

**Describe alternatives you've considered**

I've considered  using other products

**Comment by ackstorm23** [comment]
Ah, maybe this is simply a bug.  I do see a feature in preferences to auto-hide empty groups, however it never appears to take effect.

**Comment by metastable-void** [comment]
First of all, which of "Windows" panel or "Containers" panel, or both? Both have containers list inside.
Also, what do you want to do when opening a new tab in currently-empty containers? 

Above information is needed to implement this feature.

**Comment by ackstorm23** [comment]
> First of all, which of "Windows" panel or "Containers" panel, or both? Both have containers list inside. 

Windows Panel only.   A user needs to be able to switch to the containers panel to see those empty containers when this setting is turned on. 

> Also, what do you want to do when opening a new tab in one of currently-empty containers?

Hide the container until a tab exists in it. 

Or were you asking about how to create a new tab in an empty container, because its invisible before a tab exists?

**Comment by ackstorm23** [comment]
> Not to be confused with auto-hide unused containers, which seems to collapse containers with active tabs in them.

I would recommend renaming "auto-hide unused containers" to avoid confusion with the addition of this feature. 

My humble suggestion would be "auto-collapse unfocused containers"

**Comment by metastable-void** [comment]
> Or were you asking about how to create a new tab in an empty container, because its invisible before a tab exists?
Yes, I was asking that.

> Hide the container until a tab exists in it.

Is it correct that you want to hide this part of the menu hidden?
![Screenshot 2023-05-17 at 0 25 56](https://github.com/menhera-org/TabArray/assets/54881138/65c9a465-aaa2-407e-bd6b-68510dfd15fa)

**Comment by metastable-void** [comment]
By the way, container creation buttons (at the bottom of the menu) also exist next to the container search box.

**Comment by ackstorm23** [comment]
> Yes, I was asking that.

Within the Windows panel, I'm not sure the best way to do that.  Personally I would just switch to the Containers panel if I needed to create a new tab in an empty container.   

I would leave it up to you to decide that.  My concern is with not having to scroll up and down because of empty containers taking up space in the panel. 

> Is it correct that you want to hide this part of the menu hidden? ![Screenshot 2023-05-17 at 0 27 40](https://user-images.githubusercontent.com/54881138/238694699-224380ff-f37d-4948-a5ab-ad66e28fe05c.png)

The part you have  hidden appears to be what I asked for, yes.  

How would this work for Groups?  Would the empty containers simply not appear in the group they are part of?

**Comment by ackstorm23** [comment]
> By the way, container creation buttons (at the bottom of the menu) also exist next to the container search box.

That seems redundant.

**Comment by metastable-void** [comment]
> How would this work for Groups? Would the empty containers simply not appear in the group they are part of?

This is the part I am yet to decide on.

**Comment by metastable-void** [comment]
![Screenshot 2023-05-17 at 14 22 11](https://github.com/menhera-org/TabArray/assets/54881138/f4ed8514-bf0e-4fa9-8b36-75b4a3f722a8)

How about this implementation? This way, no additional setting is needed.

**Comment by metastable-void** [comment]
When you hide empty containers, they are still hidden on next reload.

**Comment by JohnLGalt** [comment]
I think that the collapsible 'unused / empty' containers section is a good fit here.

As for the duplicated controls for new container / new temp container, how about making it a part of the settings,  where user can choose 

1. at top
2. at bottom
3. both

Ultimately, I'm a big proponent for user choice, so anything and everything that is not mandatory should be user's choice whether to be displayed or not.

**Comment by metastable-void** [comment]
Minimum version of this feature has been released in the 11.10.0 release.
