### ISSUE TITLE
"Open in New Tab" does not instantiate tab adjacent to active tab

### ISSUE THREAD

**Issue by lyragordon** [menhera-org/TabArray#237]
**Describe the bug**
When opening a new tab from a hyperlink, the new tab, which should be immediately below the active tab, appears one space lower than expected.
Probably an index error. Would try to see where the issue originates, but I've never touched typescript.

**To Reproduce**
With two or more tabs open in a container, open a new tab from the first container.

**Expected behavior**
I expect the new tab to open directly below the active tab. If the tab that's getting skipped over is technically a child tab of the active tab, I have no way of knowing it, but the behavior still seems to occur when the second tab has been opened outside of the context of the active tab.

**Screenshots**
<img width="1000" alt="image" src="https://github.com/menhera-org/TabArray/assets/44142836/6a1a5230-15fc-4dd0-87e6-46f41df49ef6">

**Firefox**

 - OS: MacOS Ventura 13.3.1 (a) (22E772610a)
 - Browser edition and version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0
 - Extension version: 11.9.0.200

**Comment by metastable-void** [comment]
This (unsigned and unreleased) build should fix the issue.

[ctg-11.10.0.100-1686638777-8495a68.xpi.zip](https://github.com/menhera-org/TabArray/files/11731537/ctg-11.10.0.100-1686638777-8495a68.xpi.zip)

**Comment by metastable-void** [comment]
Should have been fixed in version 11.10.0. Please reopen if the issue persists.
