### ISSUE TITLE
[Feature Request] Ability to "roll up"/"roll down" a container

### ISSUE THREAD

**Issue by dayfuaim** [menhera-org/TabArray#3]
Now the container could only be shown or hidden. But in "normal" tab view you don't see how many containers you have, you should _know_ this.

This feature is needed because this way you can _see_ your containers and won't have to memorize and remember that.
Just like it is in Edge for example:
![Снимок экрана от 2021-12-21 14-30-02](https://user-images.githubusercontent.com/1274699/146923090-253a4be1-3527-4bf4-a55a-f0da84a50171.png)

**Comment by metastable-void** [comment]
This is technically difficult to implement, but I'll give it a try somehow.

**Comment by dayfuaim** [comment]
I understood.
It would be very good. :)

**Comment by metastable-void** [comment]
Initial implementation is done. Will be released on next update.
