### ISSUE TITLE
Options still showing after removing extension

### ISSUE THREAD

**Issue by iiKovu** [menhera-org/TabArray#318]
Option to "Open in new container" is still showing after removing the extension.

![image](https://github.com/menhera-org/TabArray/assets/83672182/68634e9d-7a2a-4d10-8a2c-9443f7698572)

I'm on Arch Linux, tried reinstalling Firefox through pacman, but that does not fix it. Also clearing cache won't.

**Comment by metastable-void** [comment]
Actually, this menu is provided by Firefox itself. This feature is enabled upon the addon installation.

To disable it, please remove the checkmark on about:preferences > General > Tabs > Enable Container Tabs.

I will let this issue open until the documentation of the procedure is done.

**Comment by iiKovu** [comment]
> Actually, this menu is provided by Firefox itself. This feature is enabled upon the addon installation.
> 
> To disable it, please remove the checkmark on about:preferences > General > Tabs > Enable Container Tabs.
> 
> I will let this issue open until the documentation of the procedure is done.

You're right, thank you very much for the quick response! It worked, I'll close the issue.

**Comment by metastable-void** [comment]
I've written the warning on the "Developer Comments" section of AMO listing page.

https://addons.mozilla.org/en-US/firefox/addon/container-tab-groups/
