### ISSUE TITLE
"No Container" New Tab opens whatever container is already open - not "No Container"

### ISSUE THREAD

**Issue by Trefa1998** [menhera-org/TabArray#374]
**Describe the bug**
When opening a new tab via the new tab button in the tabs pane by right clicking to select a container for the new tab, when selecting the top option from the drop-down (labelled "No Container"), the new tab will open in whatever the container the currently opened tab is a part of.

**To Reproduce**
Steps to reproduce the behavior (macOS Firefox Version 124.0 (64-bit)):

1. Open a new tab in a container.
2. While having a tab that is part of a container as the selected tab, right click the "New Tab" button in the tabs bar and select "No Container" (top option)
3. The newly created tab will be added to the container of the currently selected tab

**Expected behavior**
The new tab should be opened without a container.

**Firefox (please complete the following information):**

 - OS: MacOS 14.4
 - Browser edition and version: Firefox Version 124.0 (64-bit) 
 - Extension version 11.10.0.200

**Additional context**
My thought here is that when single-clicking the "New Tab" button, it opens in the same container as the currently selected tab, which is desirable; perhaps the "No Container" button is just a wrapper for the default behavior. If that is the case, I suppose the desired fix would be to have the text on the drop-down option for "No Container" to be changes to "Automatic" or "Default" and then introduce a button for "No Container" down below in the list of other available containers.

**Comment by metastable-void** [comment]
In fact, the container selection menu on the "New Tab" button is implemented on Firefox's end, and we do not have ways to customize it with WebExtensions.

The currently recommended way to open a new tab in the default container is by clicking "No Container" on the extension's menus (in sidebar/popup).

**Comment by Trefa1998** [comment]
That’s what I’ve been doing so far. Thank you for your time and reply! 

I’m closing this since it’s out of scope for the package.
