### ISSUE TITLE
Check compatibility with momentum

### ISSUE THREAD

**Issue by omares** [menhera-org/TabArray#4]
[Momentum](https://addons.mozilla.org/en-US/firefox/addon/momentumdash) is a popular new tab page replacement but it seems that the extensions are not compatible with each other. Albeit having sticky containers activated, the momentum tab opens up in a tab with no container.

Could you take a look and ensure compatibility of the extensions? Thanks!

**Comment by metastable-void** [comment]
Fixed in master.

**Comment by metastable-void** [comment]
I will upload the updated version to addons.mozilla.org later.

**Comment by metastable-void** [comment]
Fixed in version 7 (approved at AMO).
