### ISSUE TITLE
restarting firefox breaks tabs that have not fully opened yet

### ISSUE THREAD

**Issue by anarcat** [menhera-org/TabArray#457]
**Describe the bug**

When I open a URL in Firefox from the outside (say with `firefox http://example.com`), Firefox opens a new tab which, normally, prompts me for the TabArray dialog to "select a container". I don't mind that, it's great that i get to pick the right container for tabs I open, and it gives me a preview of the URL i'm about to visit, which is a nice security feature.

If, however, firefox crashes or gets restarted before I complete the process, the extension can't recover. Instead of showing the dialog prompting me to select the container, it shows a blank page.

**To Reproduce**

1. Open http://example.com/ from outside firefox, for example by typing the command `firefox http://example.com/`, so that the "Select container..." dialog is visible in a new tab
2. Restart firefox
3. Go on the same tab
4. See blank page

**Expected behavior**

Normally, it should look like this:

![image](https://github.com/user-attachments/assets/97861cfd-faac-4ad1-9fe8-a96a82838b2c)

That is, I get prompted for which container to open the page in.

**Screenshots**

What I get instead is this:

![image](https://github.com/user-attachments/assets/880d3ce7-b5fc-46ee-991a-d056a5aa956c)

Note that even it this *seems* recoverable (because of that `urlId` there, that value is essentially opaque and seems to vary even if the same URL is loaded.

**Console outputs**

(will fill up this section soon, i can't right now because i need to restart the browser, which would lose this bug report)
If applicable, open `about:debugging` > This Firefox and select Inspect for this extension. Then copy and paste what is in the console (you can hide your private information, if any).

If you cannot find any errors there, try opening the browser console (hamburger menu > more tools > browser console).

**Firefox (please complete the following information):**

 - OS: Debian GNU/Linux stable 12 "Bookworm"
 - Browser edition and version ESR 128.4.0esr-1~deb12u1
 - Extension version 11.10.0.200

**Additional context**

I don't think it's a regression, it's a problem I've been noticing for a while and only now figured I should file a bug about it. :)

**Comment by anarcat** [comment]
well, weird: i'm trying to reproduce this now and instead of the tab showing up as blank, the tab is just completely gone!

in any case, there's clearly data loss in this extension when dealing with crashes and restarts... not great :)

**Comment by metastable-void** [comment]
This is because, the extension revokes the `urlId` as soon as the 'select container' page is displayed.

Possible fix: deferring revocation until the page load occurs / making url recoverable only from the query parameters data.

**Comment by metastable-void** [comment]
Fixed in the git version. I intend to release a new version at AMO within a few weeks.
