### ISSUE TITLE
Keyboard shortcuts 

### ISSUE THREAD

**Issue by omares** [menhera-org/TabArray#5]
Could you please add keyboard shortcuts to your extension?  
Having this would enable fast switching and mouse-less usage.

Features I would like to see

- Configurable shortcut to open the quick switcher
- Configurable shortcuts to select a specific tab group
- Search field that would get focused after opening the quick switcher where one could search for tab groups or even tab titles

**Comment by metastable-void** [comment]
@anosatsuk124 Can you look at this?

**Comment by omares** [comment]
Another feature you could add is to add keyboard shortcuts (e.g. the number keys) for containers when presented with the "select container for URL from external application" view. This would allow a quick selection without having to use the mouse ;)

**Comment by anosatsuk124** [comment]
I'm working on implementing some keyboard shortcuts features. We are planning to implement only the simple keyboard shortcuts now.
Track this feature in [feature/#5_keyboard_shortcuts](https://github.com/menhera-org/TabArray/tree/feature/%235_keyboard_shortcuts).

**Comment by metastable-void** [comment]
Initial implementation of keyboard shorcuts is in the released version 11.1.0. We want to improve usability and add more shotcuts in the later releases.

**Comment by metastable-void** [comment]
In the upcoming 11.5.0 release, we can now select a popup panel by keyboard shortcuts Ctrl+Alt+[1-5].
