### ISSUE TITLE
Containers closing all tabs in them

### ISSUE THREAD

**Issue by Filip98** [menhera-org/TabArray#51]
It seems that sometimes clicking on open in new container tab or opening a new tab in the container can make the container close all tabs in it.
The closed tabs can be found in recently closed tabs and the container has only the new or copied tab in it.

Sorry I don't have the exact replication steps at this point, I will see if I can replicate it

**Comment by metastable-void** [comment]
Thank you for reporting a problem.
I'll check all points at which tabs could be closed, in the source code.
By the way, do you know how you created new container tabs when the problem happens, @Filip98 ?
(i.e. from another extension, by long-pressing browser's new tab button, by clicking a container on the extension's containers menu, by issueing Ctrl-T command, etc.)

**Comment by Filip98** [comment]
Hello, mostly by using the new tab button, I also opened a few tabs with the extension's containers menu

**Comment by metastable-void** [comment]
@Filip98 Do you have the "Index Tab" feature enabled?

**Comment by metastable-void** [comment]
If this is the case, the loophole is closed in the above commit (https://github.com/menhera-org/TabArray/commit/5c0e0532dfb158a864576fe9d9ef113683de82f4)

**Comment by Filip98** [comment]
Yes, I had index tabs enabled, I tried it with the all containers option but possibly also with "Collapsed containers".

Sorry, I've temporarily disabled the extension since I didn't want to move my tabs to the containers yet in case they get closed again so I don't have any logs.

Thanks for the quick update, I will test the new version and provide the logs if this issue happens again

**Comment by metastable-void** [comment]
The fix will be released in the upcoming 11.3.0 release. If the issue remains after the update, please let us know.

**Comment by metastable-void** [comment]
Closing as probably fixed.
