### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by xpufx** [menhera-org/TabArray#88]
```
    - Before starting a task, create a new container for it!
    - Open tabs related to the task in that container.
    - When finished, delete the container to remove all the clutters.
```

From this description it sounds like all tabs inside a container group share the same container. Is this so? That would perhaps be good for having google/youtube side by side but what if I don't want any domain within a group share a container? This is how i currently use STG which seems to use bookmarking facilities to accomplish grouping rather than containers. It works quite well with multi-account containers.

You list compatibility with multi-account containers too. How would that work? Two extensions managing containers? Would one end up having one "container tab group" per  multi-account container?

**Comment by metastable-void** [comment]
For this extension (CTG), the containers and the (tab) groups are the same and they are just the different namings, having one container for one tab group. We should perhaps improve the documentation here.

I hate different domains in a tab group sharing information in any way not intended by the user, too. That is why this extension enables the First-Party Isolate (FPI) feature of Firefox, by default. This way, storages for different domains are separated, even for a same container. It also enables natural and flicker-free openings of new windows by websites, unlike simulated FPI by manipulating containers. This is the way Tor Browser is using. I will explicitly state this fact in the documentation.

It also seems good for me if we visualize the way the cookies are separated by domain, in the cookies view. We already provide the sites view where the user can see the tabs by domain and by container. The notion of "sites" in this extension is the same as first-party domains which Firefox is using to isolate cookies.

There is a discussion whether enabling a preference in the background, even if documented, is a good idea. It is also a good thing to clearly inform the users of this feature at the first startup. I am planning of a first-launch splash screen where the user can review a few important settings, which they could also open by an explicit menu operation.

Yes, the extension Firefox Multi-account Containers and CTG together manage containers when the both are installed. They both uses the same containers. There are some unavoidable duplicate operations, but it is known that they do not break the experience. There are some features only available in CTG, for example container sorting, however.

**Comment by metastable-void** [comment]
Closing as documented.
